version: '3'

services:
  
  # Database
  db_mysql:
    image: mysql:latest
    container_name: wp_db_mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
    ##################
    # Change these credentials:
    # ################ 
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_wordpress_user
      MYSQL_PASSWORD: your_password
    # !important! these credentials must match WORDPRESS_DB_NAME, WORDPRESS_DB_USER, WORDPRESS_DB_PASSWORD
    networks:
      - wpsite

  # PHPMYADMIN
  phpmyadmin:
    container_name: wp_phpadmin
    depends_on:
      - db_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db_mysql
      MYSQL_ROOT_PASSWORD: test_root_password
    networks:
      - wpsite
  
  # Wordpress
  wordpress:
    container_name: wp_wordpress
    depends_on:
      - db_mysql
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    working_dir : /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db_mysql:3306
    ################
    # Change these credentials:
    # ################ 
      WORDPRESS_DB_NAME: your_db_name
      WORDPRESS_DB_USER: your_wordpress_user
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_TABLE_PREFIX: yourprefix_
    networks:
      - wpsite

networks:
  wpsite:
